# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - version: "3.7"
            target_base_page_id_secret: "NOTION_BASE_PAGE_ID_37"
          - version: "3.8"
            target_base_page_id_secret: "NOTION_BASE_PAGE_ID_38"
          - version: "3.9"
            target_base_page_id_secret: "NOTION_BASE_PAGE_ID_39"
          - version: "3.10"
            target_base_page_id_secret: "NOTION_BASE_PAGE_ID_310"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version.version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version.version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest --cov-config=.coveragerc --cov .
      env:
        NOTION_AUTH_TOKEN: ${{ secrets.NOTION_AUTH_TOKEN }}
        NOTION_BASE_PAGE_ID: ${{ secrets[matrix.python-version.target_base_page_id_secret] }}
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3